Regenerate nginx entries on startup
devclub-iitd/DeployBot pull request #40
Opened 2021-01-26 13:45 UTC by Harsh14901

## Changes
- Added a `-r` flag to `deploy.sh`. When this flag is set only the `nginxEntry` function is run.
- The file `src/controllers/restart.go` contains a `nginxRegenerate()` method that loops over all services and executes the `deploy.sh` script with the `-r` flag set. This method is called in `main.go` 
### TODO
- Testing whether everything works or not sequentially!
- nginx entry generation can be parallelised and go routines can be used

2021-01-26 14:07 UTC, aman71197 requested changes

2021-01-26 14:07 UTC, aagrxyz commented on scripts/deploy.sh
> +REGEN_NGINX="${REGEN_NGINX:-}"    # true = restart deploybot and regenerate nginx entries. otherwise operate normally.
Use full words unless the shortform is well known. So change it to REGENERATE_NGINX

2021-01-26 14:07 UTC, aagrxyz commented on src/controllers/restart.go
> +		_, err := exec.Command(deployScriptName, "-n", "-u", repoURL, "-b", branch, "-m", state.Server, "-s", state.Subdomain, "-a", state.Access, "-r").CombinedOutput()
Please write a function in utils that returns an array of args for a given service. Then you can also deduplicate all of this logic in deploy.go or stop.go or other places.
Then you can do something like this:
```
args := getServiceArgs(service)
args = append(args,"--regenerate_nginx")
_, err := exec.Command(deployScriptName,args...)
```

2021-01-26 14:07 UTC, aagrxyz commented on src/controllers/restart.go
> +			state.Status = "stopped"
Why are you setting state to stopped if there is an error?
The .sh script does not stop the service.

2021-01-26 14:07 UTC, aman71197 commented on src/history/history.go
> +func GetHistory() *map[string]*Service {
Do not use a direct pointer access. Please delete this method. This is not going to be thread safe. Use the `history.Services()` and then `history.SetState()`

2021-01-26 14:07 UTC, aman71197 commented on src/history/history.go
> +func GetHistory() *map[string]*Service {
Also, maps are always returned by reference in golang. See https://stackoverflow.com/questions/40680981/are-maps-passed-by-value-or-by-reference-in-go

2021-01-26 14:07 UTC, aman71197 commented on src/main.go
> +		log.Errorf("Could not regenerate NGINX template for repo: %s, details: %v", repoURL, err)
Put this before initialization of server and do a Falatf if there is an error. We do not want to start the server if there was an error in the nginx entries setup the first time.

2021-01-27 13:30 UTC, aman71197 approved these changes

2021-01-27 13:30 UTC, aman71197 commented on src/controllers/deploy.go
> +		output, err = exec.Command(deployScriptName, GetDeployArgs(a.RepoURL, branch, a.Server, a.Subdomain, a.Access)...).CombinedOutput()
Make this a separate var.
```
args = GetDeployArgs()...
exec.Command(deployScriptName,args...)
```

2021-01-28 10:33 UTC, Divi09112 commented on src/controllers/restart.go
> +		log.Infof("Nginx entry regenerated for repoURL: %s, subdomain: %s, branch: %s", repoURL, state.Subdomain, branch)
Do these for only active services. you can see if the service is running using the Status field of the repo state.

2021-01-28 12:10 UTC, merged